### ISSUE TITLE
Check string values

### ISSUE THREAD

**Issue by MikeVL** [lincolnloop/salmon#20]
I want check string values. Example check supervisor state:

```
"*":
    supervisord.status celerybeat:
        name: "Celerybeat status"
        type: boolean
        key: "celerybeat.state"
        assert: "{value} == 'RUNNING'"
```

But checker convert 'RUNNING' to True.

**Comment by supervacuo** [comment]
This feature was added a few days ago; see pull request #15

**Comment by ipmb** [comment]
String values are no longer directly supported, but the Salt modules could be tweaked to send numerical values. For example:

```
cmd.run "supervisorctl status celerybeat | grep 'RUNNING' | wc -l"
```
