### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by sc3983315** [lincolnloop/salmon#26]
after install salmon and have start succee ，when run  salmon run_checks， have a error  is  "ValueError: zero length field name in format" ,my checks.yaml  like
# cat ~/.salmon/checks.yaml

"*":
   service.status nginx:
      type: boolean
      assert: "{value} == True"

**Comment by alienzrcoming** [comment]
i'm seeing the same issue.

<pre>
cat ~/.salmon/checks.yaml 
"host1":                               # Salt target
    service.status bind9:               # Salt function(s) to run against target
        type: boolean                   # Expected result type
        assert: "{value} == True"       # Fail is this evals to False
        alert_emails:
            - email@address.com
    disk.usage:
        name: 'Disk Usage (/var)'
        type: percentage_with_sign
        key: "/.capacity"
        assert: "{value} < 80"
</pre>

**Comment by ipmb** [comment]
The `checks.yaml` file was removed in v0.2.0. Please see if it resolves your issue.
