### ISSUE TITLE
SSH to Master

### ISSUE THREAD

**Issue by brandonparsons** [lincolnloop/salmon#28]
Hi there,

You mentioned in the README it's possible to run from a server that can SSH to the master, rather than on the master itself.  Is there an example config of this somewhere? I'm not in the python community but was thinking this might be a great tool!

**Comment by ipmb** [comment]
Hi @brandonparsons this is possible by adding a line like this (uncommented) to your `conf.py` file: https://github.com/lincolnloop/salmon/blob/7936007573a8d080d4e45a44bdbab81daf0932a6/salmon/settings/base.py#L140-L141

That being said, I'm in the process of rewriting Salmon to decouple it from Salt (but be even easier to use with Salt). I'll be doing the work here: https://github.com/lincolnloop/salmon/pull/27
