### ISSUE TITLE
Release Python2.6 compatible v1

### ISSUE THREAD

**Issue by rbu** [lincolnloop/salmon#29]
The last release from 8 months ago (0.1.5) is not compatible with Python 2.6, it is missing bed0e484073cfc26d208d032cf620140e9d38e86 and 8ff6dbc302f13e6c9a9c9da0dd55024281bb270a and possibly others.
As the current master is building on 2.6 (in Travis, at least), is it possible to release it?

For users of the tool today, it makes no sense to wait until v2 will be out and not use it at all until then.

**Comment by ipmb** [comment]
v2 was just released. Let me know if you have any issues.
