### ISSUE TITLE
Changing time periods on history view

### ISSUE THREAD

**Issue by ipmb** [lincolnloop/salmon#3]
It'd be nice to change them using something like: /server.tld/?from=1d&to=5h

That would show all the history from 5 hours ago to 1 day ago.

**Comment by yml** [comment]
I have added a simple form with 2 datetimefields to represent `from_date` and `to_date`. This widget could be decorated with a date picker.

**Comment by yml** [comment]
@ipmb do you think that we should use something like http://tarruda.github.io/bootstrap-datetimepicker/ ?

**Comment by ipmb** [comment]
That would work but I think it's too complex. Many clicks are required 
to get the desired result. I'm thinking something easier like saying, "5 
hours ago" where 5 can be any positive number and hours can be 
hours/days/years. I don't have a good answer for a widget yet.

**Comment by yml** [comment]
I find the datetime pattern easier to understand. Let say I want to graph  from May 1st 00:00 to May 15th 00:00 doing the math to get the number of day + hours right is much harder than just typing  it.

**Comment by ipmb** [comment]
Makes sense. We can stick with that.
