### ISSUE TITLE
Make salmon comptaible with salt-ssh

### ISSUE THREAD

**Issue by rbu** [lincolnloop/salmon#30]
Since 0.17, salt provides the "salt-ssh" command that allows running against minions that do not have salt installed, but are configured via a roster file.
It would be nice if salmon was flexible enough to call salt or salt-ssh, depending on configuration.
It already has a configurable SALT_COMMAND, but it appends "--static", an option not allowed by salt-ssh.

**Comment by ipmb** [comment]
Please check out the new version (0.2.0) which no longer requires `SALT_COMMAND` and should work with `salt-ssh`.
