### ISSUE TITLE
Document how to access the "graph view"

### ISSUE THREAD

**Issue by arthurzenika** [lincolnloop/salmon#33]
You have  a screenshot showing some graphs, it that available ? If so how does one access it ? Is is only available for some types of metrics ? 

It would be nice to have some documentation answering the questions above.

**Comment by ipmb** [comment]
It should be available for all metrics and is accessible by clicking on the minion id on the main dashboard. The URL is `/<minion_id>/`.

Sorry for the lack of documentation, the project is still very young :)
