### ISSUE TITLE
Is this still alive? README has dead links

### ISSUE THREAD

**Issue by phryneas** [lincolnloop/salmon#37]
Hi,
the README contains some essential dead links, for example for the salmon returner.

Is this project still at a stage where it makes sense to try & deploy it, or is it dead?

**Comment by imranbhullar** [comment]
@phryneas I think the project is no more alive as I can see the last commit was about an year ago.

**Comment by phryneas** [comment]
I was hoping it would just be working so good that there was no need for more commits -.-
Do you know anything alike you can recommend?

**Comment by ipmb** [comment]
I would consider it dead. As far as I know it isn't used anywhere.

**Comment by imranbhullar** [comment]
"Yes it is dead, here is what i can see in the README"

"This project is unmaintained

My need for simple monitoring quickly became a need for more complex monitoring. I'm no longer using Salmon, as such, I'm no longer maintaining it. If you would like to continue developing Salmon, feel free to fork the repo and we can point this to your fork."
