### ISSUE TITLE
Add a note about alternative solutions

### ISSUE THREAD

**Issue by xordoquy** [lincolnloop/salmon#38]
The README file mentions:

> My need for simple monitoring quickly became a need for more complex monitoring. I'm no longer using Salmon, as such, I'm no longer maintaining it. If you would like to continue developing Salmon, feel free to fork the repo and we can point this to your fork.

I'd be really interested to know what alternative you did choose.

**Comment by ipmb** [comment]
We ended up using Graphite in the form of [graphite-api](https://github.com/brutasse/graphite-api), [carbon/whisper](https://github.com/graphite-project/carbon) and [grafana](http://grafana.org/). System metrics are collected by Salt using the scheduler and [an improved carbon returner](https://github.com/lincolnloop/salt-stats/blob/master/salt/_returners/carbon_new_return.py). We use [Heka](https://github.com/mozilla-services/heka) to collect the metrics locally on each server (and also as a statsd endpoint). Each server's Heka instance sends to a centralized Heka instance that dumps the metrics into Carbon.

**Comment by xordoquy** [comment]
Thanks for the feedback !
